export const PROJECTS = [
  {
    title: 'MERN Memories',
    image: '/images/2.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'WebRTC App',
    image: '/images/2.png',
    tags: ['React', 'WebRTC', 'React', 'WebRTC', 'React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Unichat',
    image: '/images/2.png',
    tags: ['React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Unichat',
    image: '/images/2.png',
    tags: ['React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Unichat',
    image: '/images/2.png',
    tags: ['React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
];
