export const PROJECTS = [
  {
    title: 'Reddit Clone',
    image: '/images/reddit.jpg',
    tags: [
      'Typescript',
      'React',
      'NextJS',
      'Node',
      'Express',
      'PostgreSQL',
      'TypeORM',
      'Tailwind CSS',
    ],
    source: 'https://github.com/DonaldIvan/readit',
    visit: 'http://165.22.104.71',
    id: 0,
  },
  {
    title: 'Quiz App',
    image: '/images/react-quiz.jpg',
    tags: [
      'React',
      'Typescript',
      'Netlify',
      'Github Workflow',
      'Styled Component',
    ],
    source: 'https://github.com/DonaldIvan/quiz-react-ts',
    visit: 'https://angry-carson-08965f.netlify.app/',
    id: 1,
  },
  {
    title: 'Portfolio',
    image: '/images/portfolio.jpg',
    tags: [
      'React',
      'NextJS',
      'Typescript',
      'Heroku',
      'Github Workflow',
      'Styled Component',
    ],
    source: 'https://github.com/DonaldIvan/portfolio',
    visit: 'https://donaldivancribillo.herokuapp.com/',
    id: 2,
  },
];
