export const PROJECTS = [
  {
    title: 'Portfolio',
    image: '/images/portfolio.jpg',
    tags: [
      'React',
      'NextJS',
      'Typescript',
      'Heroku',
      'Github Workflow',
      'Styled Component',
    ],
    source: 'https://github.com/DonaldIvan/portfolio',
    visit: 'https://donaldivancribillo.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Test',
    image: '/images/1.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Test',
    image: '/images/1.jpg',
    tags: ['React', 'WebRTC', 'React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Quiz App',
    image: '/images/react-quiz.jpg',
    tags: [
      'React',
      'Typescript',
      'Netlify',
      'Github Workflow',
      'Styled Component',
    ],
    source: 'https://github.com/DonaldIvan/quiz-react-ts',
    visit: 'https://angry-carson-08965f.netlify.app/',
    id: 3,
  },
];
